#70[mainRelease] fix

diff --git a/mainRelease/auto/build b/mainRelease/auto/build
--- a/mainRelease/auto/build
+++ b/mainRelease/auto/build
@@ -4,32 +4,31 @@ source config/System/system.conf
 
 set -e
 
+ISONAME=lingmo-os
+OUT=output
+
 lingmo-sys-build build noauto "${@}" 2>&1 | tee build.log
 
 # live-image-amd64.hybrid.iso 
 
-if [ -f "LingmoOS-amd64.hybrid.iso" ];then
+if [ -f "live-image-amd64.hybrid.iso" ];then
    # *.sum
-    mv LingmoOS-amd64.hybrid.iso $NAME-$BASE_VERSION-$CODE_NAME-$SYS_TYPE-$SYSTEM_TYPE-$SYSTEM_ARCH$DISK
-    md5sum ./*$DISK >> md5sum.README
-    md5sum ./*$DISK >> md5sum.txt
-    sha1sum ./*$DISK >> sha1sum.README
-    sha1sum ./*$DISK >> sha1sum.txt
-    sha256sum ./*$DISK >> sha256sum.README
-    sha256sum ./*$DISK >> sha256sum.txt
-    sha384sum ./*$DISK >> sha384sum.README
-    sha384sum ./*$DISK >> sha384sum.txt
-    sha512sum ./*$DISK >> sha512sum.README
-    sha512sum ./*$DISK >> sha512sum.txt
-    mv LingmoOS-amd64.hybrid.iso.zsync >> $NAME-$BASE_VERSION-$CODE_NAME-$SYS_TYPE-$SYSTEM_TYPE-$SYSTEM_ARCH.zsync
-    mv LingmoOS-amd64.contents >> $NAME-$BASE_VERSION-$CODE_NAME-$SYS_TYPE-$SYSTEM_TYPE-$SYSTEM_ARCH.contents
-    mkdir -p $OUT
-    mv ./*$DISK $OUT 2>/dev/null || :
-    mv ./*.zsync $OUT 2>/dev/null || :
-    mv ./*.{files,packages,contents} $OUT 2>/dev/null || :
-    mv ./*.README $OUT 2>/dev/null || :
-    mv ./*.txt $OUT 2>/dev/null || :
-    # mv ./*tar* $OUT 2>/dev/null || :
+    mv live-image-amd64.hybrid.iso $ISONAME-$BASE_VERSION-$CODE_NAME-$SYS_TYPE-$SYSTEM_TYPE-$SYSTEM_ARCH$DISK
+    mkdir -p $OUT/{iso,src}
+    mv ./$ISONAME-$BASE_VERSION-$CODE_NAME-$SYS_TYPE-$SYSTEM_TYPE-$SYSTEM_ARCH* $OUT/iso/ 2>/dev/null || :
+    mv ./live-image-source*.iso $OUT/src/$ISONAME-$CODE_NAME-$SYS_TYPE-$SYSTEM_TYPE-src.iso 2>/dev/null || :
+    mv live-image-amd64.packages $OUT/iso/$ISONAME-$BASE_VERSION-$CODE_NAME-$SYS_TYPE-$SYSTEM_TYPE-$SYSTEM_ARCH.packages 2>/dev/null || :
+    cp -v tools/make-sum $OUT/iso
+    cd $OUT/iso
+    ./make-sum
+    rm make-sum && cd ../..
+    cp -v tools/make-sum $OUT/src
+    cd $OUT/iso
+    ./make-sum
+    rm make-sum && cd ../..
+
+    echo "[Successful]All build is done"
+    
 else
-    echo "\033[34mError!"
+    echo -e "\033[34mError!"
 fi
